name: ci
on:
  push:
    branches:
      - master

jobs:
  run:
    name: Run
    runs-on: ${{ matrix.operating-system }}
    permissions:
      contents: write
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        node-version: ['16.x']
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
      - name: Install dependencies
        run: yarn install
      - name: Format code
        run: yarn format
      - name: Lint code
        run: yarn lint
      - name: Build code
        run: yarn build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
